name = "JuliaCon2020Workshops"
uuid = "525a82da-6cbc-44c3-877b-b9567f3fd09b"
authors = ["Tamás Cserteg <csertegt@gmail.com> and contributors"]
version = "0.1.0"

[deps]
GitCommand = "49b5b516-ca3f-4003-a081-42bdcf55082d"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"

[compat]
julia = "1.3"
GitCommand = "1.1"
IJulia = "1.20, 1.21"
